cms:
    resource: "@CMSBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /user

invoice:
    resource: "@InvoiceBundle/Resources/config/routing.yml"
    prefix:   /factura

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

